# Generated by Django 4.1.5 on 2023-01-14 09:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professions', '0011_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, unique=True, verbose_name='Название страницы')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='professions.profession', verbose_name='Профессия для страницы')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pages.page', verbose_name='Страница статьи')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='professions.profession', verbose_name='Профессия статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
            },
        ),
    ]
