# Generated by Django 4.1.5 on 2023-01-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profession',
            name='profession_name',
            field=models.CharField(max_length=150),
        ),
    ]
