# Generated by Django 4.1.5 on 2023-01-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_profession_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='title_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
