# Generated by Django 4.1.5 on 2023-01-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0004_rename_description_profession_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(blank=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='professions.profession', verbose_name='Профессия блога')),
            ],
        ),
    ]
