# Generated by Django 4.1.5 on 2023-01-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0006_alter_blog_options_alter_blog_table_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
