# Generated by Django 4.1.5 on 2023-01-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0009_alter_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/profession/img'),
        ),
    ]
