# Generated by Django 4.1.5 on 2023-01-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0010_alter_profession_title_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
